spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    tomcat:
      # pooling setting
      max-active: 15
      max-age: 60000
      max-idle: 2
      max-wait: 10000
      min-idle: 2
      initial-size: 2
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      validation-query: "SELECT 1"
      validation-query-timeout: 1000
